export const SIDE_QUESTS: string[] = [
  // Legend of Istoria
  "Write a Poem",
  "Pick up trash around your neighborhood",
  "Try a new food or drink",
  "Write down three things you like about yourself",
  "Legend of Istoria",
  "Take a luxurious bath or shower",
  "Organize the files on your computer",
  "Take yourself on a date",
  "LIsten to your 5 favorite songs",
  "Do a puzzle",
  "Do a 10 minute stretch",
  "Delete the apps on your phone that don't bring you joy",
  "Take 5 minutes and visualize a positive future for yourself",
  "Do 15 minutes of yoga",
  "Meditate for 10 minutes",
  "Clean out your car",
  "Take a personality quiz to learn more about yourself",
  "Light a candle or create a relaxing aroma in your space",
  "Rearrange a room",
  "Stay off social media for a day",
  "Watch a documentary",
  "Drink your favorite beverage",
  "Learn a new word and use it in a sentence",
  "Bake something",
  "Compliment someone",
  "Read a chapter from a new book",
  "Draw or paint a picture",
  "Take a walk",
  "Have your favorite meal",
  "Tell a friend you're thankful for them",
  "Set an early bedtime for more sleep",
  "Write down a favorite memory",
  "Sing your favorite song out loud",
  "Go get a new plant for your space",
  "Play a board game",
  "Do a random act of kindness",
  "Drink 5 cups of water",
  "Research your name's meaning",
  "Declutter your work space",
  "Write down the things you want to accomplish",
  "Set a timer and do 15 minutes of cleaning",
  "Try a new restaurant or recipe",
  "Spend five minutes in silent reflection",
  "Build a blanket fort",
  "Watch your favorite movie of all time",
  "Polar Bear Challenge: take a cold shower",
  "Organize your kitchen",
  "Purge your closet of old clothes you no longer wear and donate them",
  "Send a handwritten letter",
  "Make your bed",
  "Look in a mirror and say your great qualities out loud",
  "Write a 5-star review for a local small business",
  // Istoria Magic Academy
  "Stretch for 10 minutes",
  "Go on a walk around your neighborhood",
  "Make progress towards decluttering a space in your home",
  "Visit a local attraction (park, zoo, etc.)",
  "Purge your closet and donate the clothes",
  "Call someone you haven't spoken to in a while",
  "Go to a farmers market",
  "Go to a place that means a lot to you",
  "Go to a restaurant you have never tried but always wanted to",
  "Go to bed early and get an early start the next day",
  "Go to a local coffee shop",
  "Do a load of laundry",
  "Go to a dog park, with or without a dog",
  "Visit a local museum or take a virtual tour",
  "Learn and play a new board game",
  "Learn a new word",
  "Read or listen to a book for 15 minutes",
  "Learn how to say \"Hello\" in a different language",
  "Learn something new about your town's history",
  "Learn how to make a better paper airplane",
  "Learn a card or magic trick",
  "Learn how to make something with origami",
  "Practice an impression of a celebrity or character",
  "Learn a new Recipe and try to make it",
  "Memorize a new quote",
  "Learn a life skill you've wanted to learn (changing a tire, CPR, etc.)",
  "Make something with your hands",
  "Bake something from scratch",
  "Brew a special drink",
  "Write a story for 5 minutes",
  "Draw a fictional character",
  "Color for 10 minutes",
  "Take a picture of something in your house from a new perspective",
  "Make up a fictional character with a backstory",
  "Write down your favorite quote backwards and look at it in the mirror",
  "Draw or paint something that reminds you of your favorite person",
  "Put on your favorite outfit",
  "Write a poem/song about something you experience today",
  "Dance like no one is watching",
  "Light a candle",
  "Warm up a blanket in the dryer and get cozy",
  "Pause and take 10 deep breaths",
  "Get a new plant for your living space",
  "Relax your shoulders, unclench your jaw, take a deep breath.",
  "Say the ABCs backwards",
  "Do a power pose for 1 minute: stand up straight and lift your chin",
  "Spend 5 minutes alone",
  "Watch or read something that makes you laugh",
  "Watch a video of someone painting or creating something",
  "Go see a movie or watch one of your favorites at home",
  "Put your phone away and spend an hour with no internet",
  "Have some tea or a warm drink",
  // Galaxy of Istoria
  "Evade responsibilities and have a self-care day",
  "Purge a little space junk. Sell or donate something you don't use anymore",
  "Go stargazing and learn something new about constellations",
  "Draw or write about your own spacecraft. What is it for? What features does it have?",
  "Take a virtual tour of the Smithsonian National Air and Space Museum",
  "Explore the galaxy! Discover a new sci-fi movie, show, or book to enjoy!",
  "To lightspeed! Make the lighting in your space warmer and more ambient",
  "Time travel!",
  "Do something kind that your future self will appreciate",
  "\"Awesome Mix Vol. 1\"; Put together a new playlist to boost your mood",
  "Pressurize the cabin. Take ten deep, mindful breaths",
  "Launch checklist; do a brain dump; mind-map, make a list, or journal your thoughts!",
  "It's not rocket science. Learn something new about space exploration",
  "Suit up, space cadet! Set out your clothes for tomorrow",
  "Find the impostor! Remove one thing from your space that is sabotaging your best life",
  "Fix something broken in your home. If nothing's broken, learn a life hack to make a task easier.",
  "Pour and finish a tall glass of water",
  "Change up your style for a day",
  "Clean or wash your vehicle (car, bike, starship, etc.)",
  "Credits will do fine! Splurge on a more expensive version of your favorite treat",
  "Tell someone in your life that you love them -even if they already know",
  "Do some engineering! Build a Lego set or complete a puzzle",
  "Create a home-cooked meal or snack using only the ingredients in your fridge and pantry",
  "Go somewhere nearby you've never been before",
  "Clean a room in your home",
  "Review the archival data. Binge-watch your favorite show with zero shame",
  "Send a message through time. Write a one-page letter to yourself, to be read exactly one year from now.",
  "Create your own planet. Write/draw the details of the landscape!",
  "Take a quick nap with your feet up",
  "Pick out your best pair of socks and wear them today",
  "Prepare for the next invasion. Work out for 10 minutes!",
  "Write a letter or email to an astronaut! (find mailing info on Nasa's website)",
  "Always carry a towel! Wash all the towels in your home.",
  "Writing prompt: narrate your day as excitingly as possible (exaggerations welcome!)",
  "Read by candlelight",
  "Discover a new star! Learn how to make origami stars",
  "Enter cryosleep. Go to bed early tonight, or sleep in tomorrow morning",
  "Hang an inspirational poster or picture where you will see it often",
  "Break down a large overwhelming challenge into smaller tasks",
  "Prepare the sleeping pod. Make your bed all nice and tidy.",
  "Take a 5 minute meditation. Breathe and ground yourself.",
  "Open the pod bay doors! Spend some time out in nature",
  "Beam down to Earth! Stand barefoot in the grass",
  "Do something to support your health and/or prosperity.",
  "Visit an aquarium or pet store, or watch some relaxing fish videos",
  "Bring vegetation to your homeworld! Get a new plat for your home.",
  "Terraform your amosphere! Tidy up or get rid of any clutter that's disrupting your peace of mind",
  "Take a break from tech for a few hours",
  "Make astronaut food! Prep a few healthy meals for the journey ahead",
  "Contact a friendly lifeform. Call or text a friend just because",
  "Use the Force! Connect with your spiritual self through mindfulness or meditation exercises",
  "Step into the regeneration pod! Take a long shower or bath",
  "Assemble your crew. Make a list of five important people in your life and what you love about them."
];
